"""Portas: o que a aplicacao precisa do mundo externo."""
from pathlib import Path
from typing import Callable, ContextManager, Iterable, Optional, Protocol

from ..dominio.conta import Conta, Perfil
from ..dominio.galeria import ItemGaleria
from ..dominio.preferencias import Preferencias
from ..dominio.skin import Skin
from ..dominio.versao import NovaVersao

Progresso = Callable[..., None]
Preencher = Callable[[Path], None]


class RepositorioSkins(Protocol):
    usuario: Path
    def listar(self) -> list[Skin]: ...
    def novo_id(self, nome: str) -> str: ...
    def gravar(self, skin: Skin, preencher: Optional[Preencher] = None,
               capa: Optional[Path] = None) -> Skin: ...
    def copiar(self, origem: Skin, nova: Skin) -> Skin: ...
    def excluir(self, skin: Skin) -> None: ...
    def definir_capa(self, skin: Skin, imagem_png: Path) -> None: ...
    def exportar(self, skin: Skin, arquivo: str) -> str: ...
    def importar(self, caminho: Path, autor: str) -> Skin: ...
    def gravar_desfazer(self, preencher: Preencher, estava_ativa: Optional[str]) -> None: ...
    def desfazer_disponivel(self) -> Optional[Skin]: ...
    def desfazer_temporario(self) -> ContextManager[Skin]: ...


class Desktop(Protocol):
    def verificar(self) -> None: ...
    def capturar(self, destino: Path, leve: bool = False, progresso: Progresso = ...) -> bool:
        """Grava o visual da tela em `destino`. Devolve se o dock esta ligado."""
    def aplicar(self, skin: Skin, prefs: Preferencias, progresso: Progresso = ...) -> list[str]:
        """Aplica a skin. Devolve avisos (nao fatais)."""
    def corresponde(self, skin: Skin) -> bool: ...
    def restaurar_tela_login(self) -> None: ...


class Estado(Protocol):
    def sessao(self) -> Optional[str]: ...
    def definir_sessao(self, token: Optional[str]) -> None: ...
    def ler_valor(self, chave: str, padrao=None): ...
    def gravar_valor(self, chave: str, valor) -> None: ...
    def skin_ativa(self) -> Optional[str]: ...
    def definir_ativa(self, skin_id: Optional[str]) -> None: ...
    def preferencias(self) -> Preferencias: ...
    def gravar_preferencias(self, prefs: Preferencias) -> None: ...


class Migrador(Protocol):
    def migrar(self) -> Iterable[Skin]: ...


class Nuvem(Protocol):
    """Contas, galeria e skins guardadas na conta. Hoje: pasta local; depois: servidor."""
    def criar_conta(self, nome: str, email: str, senha: str) -> tuple: ...
    def entrar(self, email: str, senha: str) -> tuple: ...
    def sair(self, token: str) -> None: ...
    def conta(self, token: str) -> Optional[Conta]: ...
    def enviar(self, token: str, pasta: Path, meta: dict, publica: bool,
               item_id: Optional[str] = None) -> ItemGaleria: ...
    def galeria(self) -> list[ItemGaleria]: ...
    def da_conta(self, token: str) -> list[ItemGaleria]: ...
    def item(self, item_id: str, token: Optional[str] = None) -> ItemGaleria: ...
    def baixar(self, item_id: str, token: Optional[str] = None) -> Path: ...
    def definir_publica(self, token: str, item_id: str, publica: bool) -> None: ...
    def remover(self, token: str, item_id: str) -> None: ...
    def favoritar(self, token: str, item_id: str, favorito: bool) -> None: ...
    def favoritos(self, token: str) -> set: ...
    def contagem_favoritos(self, item_id: str) -> int: ...
    def perfil(self, autor_id: str) -> Optional[Perfil]: ...


class Atualizacoes(Protocol):
    def ultima_versao(self) -> Optional[NovaVersao]: ...
    def baixar(self, nova: NovaVersao, destino: Path) -> Path: ...
    def instalar(self, pacote: Path) -> None: ...
